FROM node:18.16.0-alpine as build

RUN npm install -g typescript

WORKDIR /usr/src/app

COPY package.json ./

COPY . .

RUN npm install --legacy-peer-deps

RUN npm run build

FROM nginx:stable-alpine as prod

EXPOSE 80
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
